### ISSUE TITLE
openauto freezes if connected wireless and loses wifi

### ISSUE THREAD

**Issue by WarDrake** [f1xpl/openauto#58] opened 2018-04-02 21:14 UTC
If the wireless connection is lost (walk away and take the phone after done driving) while openauto is connected wirelessly the application freezes and all input is disregarded, be it mouse/keyboard/touch

can't connect trough ssh anymore either, but if you stay within range for a couple minutes the system connects back to the wifi, however openauto stays frozen and the system not responsive.

**Comment by f1xpl** [comment] 2018-04-04 08:30
Looks like the problem is related to the TCP keep alive mechanism.

**Comment by f1xpl** [comment] 2018-04-05 23:09
Correction has been merged to the development branch. OpenAuto will close connection after ~10 seconds when broken link has been detected. In order to test it please clone and compile latest development branch of aasdk and openauto projects.

**Comment by WarDrake** [comment] 2018-04-06 04:58
I checked out and compiled both Development versions, Fix works as intended, after a few seconds of the wifi being lost, openauto now returns to the connection screen and doesn't freeze anymore.

**Comment by f1xpl** [comment] 2018-04-07 11:53
Merged to master.

**Closed by f1xpl** 2018-04-07 11:53 UTC
Labels: bug
